os: linux
dist: focal
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  - docker pull fr3akyphantom/droid-builder:focal
  - cd $HOME && mkdir twrp
  - git config --global user.name "Vincent Loupmon"
  - git config --global user.email 6957532+Vloupmon@users.noreply.github.com
  - git config --global color.ui true
script:
  - |
    docker run --rm -i --user $(id -u):$(id -g) -v "${HOME}/.gitconfig:/home/builder/.gitconfig:rw,z" -v "${HOME}/twrp:/home/builder/twrp:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" -w /home/builder/twrp fr3akyphantom/droid-builder:focal bash << EOF
    repo init --depth=1 -q -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
    repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
    git clone https://github.com/Vloupmon/TWRP_Realme_RMX3085.git device/alps/oppo6785
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
    BUILD_FLAVOR="eng"
    lunch twrp_oppo6785-${BUILD_FLAVOR}
    mka recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/oppo6785/recovery.img $HOME/twrp/TWRP-$version-oppo6785-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  - curl -s --upload-file TWRP-$version-oppo6785-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  # The secret api_key will be loaded from the environment variables
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: Vloupmon/TWRP_Realme_RMX3085 # Optional: If you want to deploy on different repository
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
