os: linux
dist: focal
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - git-core
      - curl
      - libssl-dev
      - gnupg
      - flex
      - bison
      - build-essential
      - zip
      - unzip
      - zlib1g-dev
      - gcc-multilib
      - g++-multilib
      - libc6-dev-i386
      - lib32ncurses5-dev
      - x11proto-core-dev
      - libx11-dev
      - lib32z1-dev
      - libgl1-mesa-dev
      - libxml2-utils
      - xsltproc
      - fontconfig
      - kpartx
      - sudo
      - dosfstools
      - rsync
      - libncurses5
      - python3-mako
      - netcat
before_install:
  - cd $HOME
    # Setup .gitconfig
  - git config --global user.name "Vincent Loupmon"
  - git config --global user.email 6957532+Vloupmon@users.noreply.github.com
  - git config --global color.ui true
    # Installing git-repo manually as it doesn't exist in Ubuntu focal's repos
  - mkdir -p ~/.bin
  - PATH="${HOME}/.bin:${PATH}"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
  - chmod a+rx ~/.bin/repo
before_script:
   # Refresh ENV variables
  - eval "$(exec /usr/bin/env -i "${SHELL}" -l -c "export")"
  - mkdir ${HOME}/twrp
script:
  - cd ${HOME}/twrp
  - repo init --depth=1 -q -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
  - repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
  - git clone https://github.com/Vloupmon/TWRP_Realme_RMX3085.git device/alps/oppo6785
  - export ALLOW_MISSING_DEPENDENCIES=true
  - source build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
  - BUILD_FLAVOR="eng"
  - lunch twrp_oppo6785-${BUILD_FLAVOR}
  - mka recoveryimage
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - find ${HOME}/twrp/out | nc termbin.com 9999
  - tar -zcvf out.tar.gz ${HOME}/twrp/out
  - curl -s --upload-file out.tar.gz https://transfer.sh/ && echo ""
  - exit 1
  #- cp ${HOME}/twrp/out/target/product/oppo6785/recovery.img ${HOME}/twrp/TWRP-$version-oppo6785-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  - curl -s --upload-file TWRP-$version-oppo6785-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  # The secret api_key will be loaded from the environment variables
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: Vloupmon/TWRP_Realme_RMX3085 # Optional: If you want to deploy on different repository
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
